# Generated by Django 4.1.4 on 2023-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('ethnicity', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('allergies', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
            ],
        ),
    ]
