# Generated by Django 4.1.4 on 2023-03-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medical_history',
            new_name='medicalHist_conditions',
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalHist_mental',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalHist_pastSurgery',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalHist_sexual',
            field=models.TextField(blank=True),
        ),
    ]
