# Generated by Django 4.1.4 on 2023-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_medical_history_patient_medicalhist_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medicalHist_medication',
            field=models.TextField(blank=True),
        ),
    ]
