# Generated by Django 4.1.4 on 2023-03-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient_medicalhist_medication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
