# Generated by Django 4.1.4 on 2023-03-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_patient_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugsPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=500)),
                ('expiry_date', models.DateField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
