# Generated by Django 4.1.4 on 2023-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_drugspharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('test_type', models.CharField(choices=[('BT', 'Blood Test'), ('MRI', 'MRI'), ('XRAY', 'X-Ray')], max_length=4)),
                ('lab_result_notes', models.TextField()),
                ('medical_image', models.FileField(upload_to='test_results/')),
            ],
        ),
    ]
