# Generated by Django 4.1.4 on 2023-04-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
