# Generated by Django 4.1.4 on 2023-04-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
