# Generated by Django 4.1.4 on 2023-04-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
