# Generated by Django 4.1.4 on 2023-04-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=255)),
                ('temperature', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('visual_exam', models.TextField(blank=True)),
                ('physical_exam', models.TextField(blank=True)),
                ('other_notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patients')),
            ],
        ),
    ]
