# Generated by Django 4.1.4 on 2023-04-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_consultations_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
