# Generated by Django 4.1.4 on 2023-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_consultations_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultations',
            name='doctor',
            field=models.CharField(max_length=255),
        ),
    ]
