# Generated by Django 4.1.4 on 2023-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_consultations_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='medicalHist_conditions',
            new_name='Medical_Surgical_History',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='ethnicity',
            new_name='nationality',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medicalHist_medication',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medicalHist_mental',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medicalHist_pastSurgery',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medicalHist_sexual',
        ),
        migrations.AlterField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
