# Generated by Django 4.1.4 on 2023-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_medicalhist_conditions_patients_medical_surgical_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Medical_Surgical_History',
        ),
        migrations.AddField(
            model_name='patients',
            name='medical_surgical_history',
            field=models.ManyToManyField(blank=True, to='app.medicalsurgicalhistory'),
        ),
    ]
