# Generated by Django 4.1.4 on 2023-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_medicalsurgicalhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='medical_surgical_history',
        ),
        migrations.DeleteModel(
            name='MedicalSurgicalHistory',
        ),
        migrations.AddField(
            model_name='patients',
            name='Medical_Surgical_History',
            field=models.TextField(blank=True),
        ),
    ]
