# Generated by Django 4.1.4 on 2023-04-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('Blood Test', 'Blood Test'), ('MRI', 'MRI'), ('XRAY', 'X-Ray')], max_length=10)),
                ('lab_result_notes', models.TextField()),
                ('medical_image', models.FileField(upload_to='test_results/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patients')),
            ],
        ),
    ]
